version: '3.9'
services:
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: always
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "80:80"    # http
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS}:/var/log/nginx

  database:
    # default port 3306
    image: mysql:8
    container_name: wp-database
    env_file:
      - .env
    restart: always
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp-wordpress
    env_file:
      - .env
    restart: always
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
  composer:
    image: composer/composer
    container_name: myapp-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 8080
#    image: adminer:4
#    container_name: wp-adminer
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    ports:
#      - "9000:8080"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge